//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selection.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID0001;i3;500GB;4GB
        ///ID0002;i3;500GB;4GB
        ///ID0003;i3;500GB;4GB
        ///ID0004;i3;500GB;4GB
        ///ID0005;i3;500GB;4GB
        ///ID0006;i3;500GB;4GB
        ///ID0007;i3;500GB;4GB
        ///ID0008;i3;500GB;4GB
        ///ID0009;i3;500GB;4GB
        ///ID0010;i3;500GB;4GB
        ///ID0011;i3;500GB;4GB
        ///ID0012;i3;500GB;4GB
        ///ID0013;i3;500GB;4GB
        ///ID0014;i3;500GB;4GB
        ///ID0015;i3;500GB;4GB
        ///ID0016;i3;500GB;4GB
        ///ID0017;i3;500GB;4GB
        ///ID0018;i3;500GB;4GB
        ///ID0019;i3;500GB;4GB
        ///ID0020;i3;500GB;4GB
        ///ID0021;i3;500GB;4GB
        ///ID0022;i3;500GB;4GB
        ///ID0023;i3;500GB;4GB
        ///ID0024;i3;500GB;4GB
        ///ID0025;i [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string pcs {
            get {
                return ResourceManager.GetString("pcs", resourceCulture);
            }
        }
    }
}
